---
- hosts: localhost
  vars:
    plbook: desktop

  tasks:
    # -----------------------------------
    - name: install packages
      community.general.pacman:
        # install_recommends: true
        state: present
        name:
          - arcolinux-teamviewer
          - budgie-screensaver  
          - cherrytree
          - geeqie
          - google-chrome
          - libreoffice-still
#          - megasync-bin
          - minder
          - nemo
          - nemo-fileroller 
          - nemo-preview
          - ocrmypdf
          - pdfarranger
          - pdftk
          - teams
          - slack-desktop
          - thunderbird
          - variety
          - vlc
          - deepin-screenshot
