---
- hosts: localhost
  vars:
    plbook: graphics

  tasks:
    # -----------------------------------
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      #        autoremove: yes
      #        autoclean: yes

    # -----------------------------------
    - name: dpk-hist-before
      shell: "apt list --installed >dpkg-hist/$(hostname -s)_$(date +%y%m%d-%H%M)_dpkgs_before_{{ plbook }}.txt"

    # -----------------------------------
    - name: install packages
      apt:
        install_recommends: true
        state: latest
        name:
          - exiftran
          - exiv2
          - geeqie
          - gimp
          - imagemagick
          - rawtherapee

    # -----------------------------------
    - name: dpk-hist-after
      shell: "apt list --installed >dpkg-hist/$(hostname -s)_$(date +%y%m%d-%H%M)_dpkgs_after_{{ plbook }}.txt"
