---
- hosts: localhost
  vars:
    plbook: graphics

  tasks:
    # -----------------------------------
    - name: install packages
      community.general.pacman:
        state: present
        name:
          - enblend-enfuse
          - fbida
          - exiv2
          - geeqie
          - gimp
          - hugin
          - imagemagick
          - rawtherapee
