---
- hosts: localhost
  tasks:
    - name: visualstudio code key
      apt_key:
        url: 'https://packages.microsoft.com/keys/microsoft.asc'
        state: present
    - name: visualstudio code repo
      apt_repository:
        repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
        state: present
        filename: 'visualstudio-code'

#    - name: xxx key
#      apt_key:
#        url: 'xxxurl'
#        state: present
#    - name: xxx repo
#      apt_repository:
#        repo: 'xxxrepo'
#        filename: 'xxxrepo'
#        state: present

        # -----------------------------------
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
       
        # -----------------------------------
    - name: install packages
      apt:
        state: present
        name:
         - code
