---
- hosts: localhost
  vars:
    plbook: develop

  tasks:
    - name: visualstudio code key
      apt_key:
        url: 'https://packages.microsoft.com/keys/microsoft.asc'
        state: present
    - name: visualstudio code repo
      apt_repository:
        repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
        state: present
        filename: 'visualstudio-code'

#    - name: xxx key
#      apt_key:
#        url: 'xxxurl'
#        state: latest
#    - name: xxx repo
#      apt_repository:
#        repo: 'xxxrepo'
#        filename: 'xxxrepo'
#        state: latest

        # -----------------------------------
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
       
    # -----------------------------------
    - name: dpk-hist-before
      shell: "apt list --installed >dpkg-hist/$(hostname -s)_$(date +%y%m%d-%H%M)_dpkgs_before_{{ plbook }}.txt"

        # -----------------------------------
    - name: install packages
      apt:
        state: latest
        name:
         - code
         - gambas3

    # -----------------------------------
    - name: dpk-hist-after
      shell: "apt list --installed >dpkg-hist/$(hostname -s)_$(date +%y%m%d-%H%M)_dpkgs_after_{{ plbook }}.txt"
