---
- hosts: localhost
  vars:
    plbook: develop

  tasks:
    # -----------------------------------
    - name: install packages
      community.general.pacman:
        state: present
        name:
#        - code
          - gambas3-ide
          - git
          - gitg
          - vscodium-bin
