---
- hosts: localhost
  vars:
    plbook: system

  tasks:
    # -----------------------------------
    - name: install packages
      community.general.pacman:
      # install_recommends: true
        state: present
        name:
          - amd-ucode
